### ISSUE TITLE
Exception when no line available

### ISSUE THREAD

**Issue by suterma** [suterma/CopyForReview#8]
Here's my code (in snippet.cs):

    var commonIndent =
        (from line in Lines
            where (IsNonEmpty(line))
            select GetLeadingWhitespaceCount(line)).Min();
    return commonIndent;

System.InvalidOperationException was unhandled by user code
  HResult=-2146233079
  Message=Sequence contains no elements
  Source=System.Core
  StackTrace:
       at System.Linq.Enumerable.Min(IEnumerable`1 source)
       at Codeministry.CopyForReview.Data.Snippet.CommonIndent() in c:\Users\marcel\Documents\CopyForReview\Source\Codeministry.CopyForReview.Data\Snippet.cs:line 143
       at Codeministry.CopyForReview.Data.Snippet.get_DeindentedLines() in c:\Users\marcel\Documents\CopyForReview\Source\Codeministry.CopyForReview.Data\Snippet.cs:line 115
       at Codeministry.CopyForReview.Data.Snippet.get_DeindentedSelectedText() in c:\Users\marcel\Documents\CopyForReview\Source\Codeministry.CopyForReview.Data\Snippet.cs:line 38
  InnerException:

**Comment by suterma** [comment]
Fixed by having a default of zero when there are only empty lines
